# simulation dependent parameters
temps: [0.45, 0.47, 0.49, 0.51, 0.53, 0.55, 0.58, 0.61, 0.64, 0.67, 0.7, 0.75, 0.8, 0.9, 1.0]
pairs_phis: [
  [["KA_ModLJ", "0.2"], "1.1"],
  [["KA_ModLJ", "0.3"], "1.05"]
]

# constant details of all sims
dt: 1.0e-3
start_index: -1
dump_rate: 1
sim_time: 10_000
throw_away: 10_000

# meta
in_dir_tag: "run2"
out_dir_tag: "run2"
starting_seed: 30
