# simulation dependent parameters
temps: [0.45, 0.47, 0.49, 0.51, 0.53, 0.55, 0.58, 0.61, 0.64, 0.67, 0.7, 0.75, 0.8, 0.9, 1.0]
pairs_phis: [
  [["KA_LJ"], "1.2"],
  [["KA_ModLJ", "0.1"], "1.15"]
]

# constant details of all sims
N: 4096
dt: 1.0e-3
start_temp: 1.5
equil_time: 1_000
quench_rate: 1.0e-3
dump_rate: 100
sim_time: 100_000
throw_away: 0

# meta
dir_tag: "run1"
starting_seed: 0