# configfile: "config.yaml"

# prepend monk dataset path
def dd(post_path):
    import os
    tmp = os.environ["MONK_DATA_DIR"] + "/monk/" + post_path
    return tmp

def get_all():
    outputs = []
    for temp in config["temps"]:
        print(temp)
        for pair_phi in config["pairs_phis"]:
            tpair = '-'.join(pair_phi[0])
            tphi = pair_phi[1]
            outputs.append(dd(f"supercooled_states/{config['dir_tag']}/pair-{tpair}_phi-{tphi}/temp-{temp}.gsd"))

    return outputs

rule all:
    input: 
        *get_all()

rule equilibrate:
    output:
        dd("supercooled_states/{dir_tag}/pair-{pair}_phi-{phi}/temp-{temp}.gsd")
    params:
        split_pair=lambda wildcards: wildcards.pair.split("-"),
        num=config["N"],
        dt=config["dt"],
        start_temp=config["start_temp"],
        equil_time=config["equil_time"],
        quench_rate=config["quench_rate"],
        dump_rate=config["dump_rate"],
        sim_time=config["sim_time"]
    resources:
        time="3-00:00:00",
        gpu=1,
        mem_mb=1000
    shell:
        "python ../../../scripts/nvt/quench_and_equil.py {output} "
        "--num {params.num} --pair {params.split_pair} --dt {params.dt} --phi {wildcards.phi} "
        "--temps {params.start_temp} {wildcards.temp} --equil-time {params.equil_time} "
        "--quench-rate {params.quench_rate} --dump-rate {params.dump_rate} "
        "--sim-time {params.sim_time}"
